# Generated by Django 3.0.8 on 2020-07-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0002_auto_20200709_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=15, verbose_name='ФИО')),
                ('personnel_number', models.CharField(max_length=15, verbose_name='Табельный номер')),
            ],
        ),
        migrations.CreateModel(
            name='VievLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viev_limit', models.CharField(max_length=15, verbose_name='Вид лимита')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='limit',
            field=models.IntegerField(default=0, verbose_name='Лимит'),
        ),
        migrations.AddField(
            model_name='card',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Holder'),
        ),
        migrations.AddField(
            model_name='card',
            name='viev_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.VievLimit'),
        ),
    ]
