# Generated by Django 3.0.8 on 2020-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0003_auto_20200709_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='holder',
            field=models.CharField(max_length=40, verbose_name='ФИО'),
        ),
    ]
