# Generated by Django 3.0.8 on 2020-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0005_car_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(max_length=50, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=50, null=True, verbose_name='Vin номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_issue',
            field=models.CharField(max_length=50, null=True, verbose_name='Год'),
        ),
    ]
