# Generated by Django 3.0.8 on 2020-07-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0007_auto_20200709_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='government_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Car'),
        ),
    ]
