# Generated by Django 3.0.8 on 2020-07-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0008_card_government_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Транспортные средства', 'verbose_name_plural': 'Транспортное средство'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Топливные карты', 'verbose_name_plural': 'Топливная карта'},
        ),
    ]
