# Generated by Django 3.0.8 on 2020-07-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0009_auto_20200709_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='holder',
            options={'verbose_name': 'Держатель', 'verbose_name_plural': 'Держатели'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(db_column='Модель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.CarModel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_nomenclature',
            field=models.ForeignKey(db_column='Номенклатура', null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Nomenclature'),
        ),
    ]
