# Generated by Django 3.0.8 on 2020-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0010_auto_20200709_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.CarModel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Nomenclature', verbose_name='Номенклатура'),
        ),
    ]
