# Generated by Django 3.0.8 on 2020-07-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0011_auto_20200709_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_column', models.CharField(max_length=30, verbose_name='Колонна')),
            ],
        ),
        migrations.AlterModelOptions(
            name='limittipe',
            options={'verbose_name': 'Тип лимита', 'verbose_name_plural': 'Типы лимитов'},
        ),
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='vievlimit',
            options={'verbose_name': 'Вид лимита', 'verbose_name_plural': 'Виды лимитов'},
        ),
        migrations.AlterField(
            model_name='card',
            name='government_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Car', verbose_name='Государственный номер'),
        ),
        migrations.AlterField(
            model_name='card',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Holder', verbose_name='Держатель'),
        ),
        migrations.AlterField(
            model_name='card',
            name='limit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.LimitTipe', verbose_name='Тип лимита'),
        ),
        migrations.AlterField(
            model_name='card',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.Nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='card',
            name='viev_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_gsm.VievLimit', verbose_name='Вид лимита'),
        ),
    ]
