# Generated by Django 3.0.8 on 2020-07-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_gsm', '0012_auto_20200709_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'Колонна', 'verbose_name_plural': 'Колонны'},
        ),
    ]
